language: scala

jdk:
  - openjdk8
  - openjdk11

env:
  - SCALA_VERSION=2.11.6
  - SCALA_VERSION=2.11.7
  - SCALA_VERSION=2.11.8
  - SCALA_VERSION=2.11.11
  - SCALA_VERSION=2.11.12
  - SCALA_VERSION=2.12.3
  - SCALA_VERSION=2.12.4
  - SCALA_VERSION=2.12.6
  - SCALA_VERSION=2.12.7
  - SCALA_VERSION=2.12.8
  - SCALA_VERSION=2.12.9
  - SCALA_VERSION=2.12.10
  - SCALA_VERSION=2.13.0
  - SCALA_VERSION=2.13.1

# 2.11.12 was the first Scala 2.11.x version to work on jdk11
matrix:
  exclude:
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.6
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.7
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.8
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.11

script:
  # Increasing ReservedCodeCacheSize minimizes scala compiler-interface compile times
  - sbt -J-XX:ReservedCodeCacheSize=256M ++$SCALA_VERSION test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
