language: scala

env:
  - SCALA_VERSION=2.11.6
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.11.7
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.11.8
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.11.11
    TRAVIS_JDK=adopt@1.8.0-222
  # 2.11.12 was the first Scala 2.11.x version to work on jdk11
  - SCALA_VERSION=2.11.12
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.11.12
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.3
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.3
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.4
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.4
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.6
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.6
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.7
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.7
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.8
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.8
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.9
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.9
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.12.10
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.12.10
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.13.0
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.13.0
    TRAVIS_JDK=adopt@1.11.0-4
  - SCALA_VERSION=2.13.1
    TRAVIS_JDK=adopt@1.8.0-222
  - SCALA_VERSION=2.13.1
    TRAVIS_JDK=adopt@1.11.0-4

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

stages:
  - name: test
  - name: release
    if: tag =~ ^v AND NOT fork

jobs:
  include:
    - stage: test
      # Increasing ReservedCodeCacheSize minimizes scala compiler-interface compile times
      script: sbt -J-XX:ReservedCodeCacheSize=256M ++$SCALA_VERSION test
    - stage: release
      script: sbt ci-release

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
